addSbtPlugin("com.eed3si9n"  % "sbt-projectmatrix" % "0.10.1")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix"      % "0.14.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"      % "2.5.4")
addSbtPlugin("org.scala-js"  % "sbt-scalajs"       % "1.18.2")
addSbtPlugin("org.typelevel" % "sbt-tpolecat"      % "0.5.2")
